config/routes.rb
Rails.application.routes.draw do
  resources :guestreviews
  resources :accommodationreviews
  resources :stays 
  resources :messages, only: [:create, :destroy]
  resources :accommodations
  resources :profiles
  devise_for :users
  resources :charges
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "pages#index"

  get "guest/:guest_id/stays" => "stays#index", as: "guest_stays"
  get "accommodation/:accommodation_id/stays" => "stays#index", as: "accommodation_stays"
  get "pages/about" => "pages#about", as: "about_page"
  get "pages/upgrade" => "pages#upgrade", as: "upgrade"
  get "stay/update-status" => "stays#update_status", as: "update_status"
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :stay
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @stay = Stay.find(params[:message][:stay_id])
    if params[:message][:guest_id]
      @guest = User.find(params[:message][:guest_id])
    elsif params[:message][:accommodation_id]
      @accommodation = Accommodation.find(params[:message][:accommodation_id])
    end
    @message = Message.new(message_params)
    @message.created_at = Time.now
    respond_to do |format|
      if @message.save!
        if params[:message][:accommodation_id]
          format.html { redirect_to stay_path(@stay, accommodation_id: @accommodation.id), notice: 'Message was successfully created.' }
          format.json { render :show, status: :created, location: @message }
        elsif params[:message][:guest_id]
          format.html { redirect_to stay_path(@stay, guest_id: @guest.id), notice: 'Message was successfully created.' }
          format.json { render :show, status: :created, location: @message }
        end
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @stay = Stay.find(params[:stay_id])
    if params[:guest_id]
      @guest = User.find(params[:guest_id])
    elsif params[:accommodation_id]
      @accommodation = Accommodation.find(params[:accommodation_id])
    end

    @message.destroy
    respond_to do |format|
      if params[:accommodation_id]
        format.html { redirect_to stay_path(@stay, accommodation_id: @accommodation.id), notice: 'Message was successfully destroyed.' }
        format.json { head :no_content }
      elsif params[:guest_id]
        format.html { redirect_to stay_path(@stay, guest_id: @guest.id), notice: 'Message was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:content, :created_at, :stay_id, :user_id)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_with(model: message, local: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :created_at %>
    <%= form.datetime_select :created_at %>
  </div>

  <div class="field">
    <%= form.label :stay_id %>
    <%= form.text_field :stay_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/_guest_form.html.erb
<div class="form-inline">
  <%= form_with(model: message, local: true) do |form| %>
    <% if message.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

        <ul>
        <% message.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field valign">
      <%= form.label :content, 'Message:' %>
      <%= form.text_area :content, class: 'devise-field' %>
    </div>

    <%= form.hidden_field :stay_id, value: stay_id %>
    <%= form.hidden_field :user_id, value: user_id %>
    <%= form.hidden_field :guest_id, value: guest_id %>
    <%= form.submit class: 'message-button' %>
  <% end %>
</div>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Created at</th>
      <th>Stay</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.content %></td>
        <td><%= message.created_at %></td>
        <td><%= message.stay %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @message.content %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @message.created_at %>
</p>

<p>
  <strong>Stay:</strong>
  <%= @message.stay %>
</p>

<%= link_to 'Edit', edit_message_path(@message, stay_id: @message.stay.id) %> |
<%= link_to 'Back', messages_path %>