config/routes.rb
Rails.application.routes.draw do
  resources :guestreviews
  resources :accommodationreviews
  resources :stays 
  resources :messages, only: [:create, :destroy]
  resources :accommodations
  resources :profiles
  devise_for :users
  resources :charges
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "pages#index"

  get "guest/:guest_id/stays" => "stays#index", as: "guest_stays"
  get "accommodation/:accommodation_id/stays" => "stays#index", as: "accommodation_stays"
  get "pages/about" => "pages#about", as: "about_page"
  get "pages/upgrade" => "pages#upgrade", as: "upgrade"
  get "stay/update-status" => "stays#update_status", as: "update_status"
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  validates :bio, length: { maximum: 200 }
  has_one_attached :uploaded_image

  def update_host_rating(rating)
    # calculate total reviews by counting stay reviews
    host_review_count = 0

    self.user.accommodation.stays.each do |stay|
      if stay.accommodationreview
        host_review_count =  host_review_count + 1
      end
    end

    # add new rating to current rating
    self.host_rating = self.host_rating + rating.to_i
    self.save!
  end

  def get_host_rating()
    # calculate total reviews by counting stay reviews
    host_review_count = 0
    
    if self.user.accommodation
      self.user.accommodation.stays.each do |stay|
        if stay.accommodationreview
          host_review_count =  host_review_count + 1
        end
      end
      
      # divide rating by total stays
      if host_review_count != 0
        average_rating = self.host_rating / host_review_count
      else
        average_rating = 0
      end

    end

    return average_rating
  end


  def update_guest_rating(cleanliness_rating, communication_rating, ease_of_hosting_rating)

    guest_stays = Stay.where(guest_id: self.user.id)
 
    # calculate total reviews by counting stay reviews
    guest_review_count = 0

    guest_stays.each do |stay|
      if stay.guestreview
        guest_review_count =  guest_review_count + 1
      end
    end

    # Get average of this user's ratings
    users_average_rating = calculate_average([cleanliness_rating.to_i, communication_rating.to_i, ease_of_hosting_rating.to_i])

    # add new rating to current guest rating
    self.guest_rating = self.guest_rating + users_average_rating
    self.save!
  end

  def get_guest_rating()
    guest_stays = Stay.where(guest_id: self.user.id)

    # calculate total reviews by counting stay reviews
    guest_review_count = 0

    guest_stays.each do |stay|
      if stay.guestreview
        guest_review_count =  guest_review_count + 1
      end
    end

    # divide rating by total stays
    if guest_review_count != 0
      average_rating = self.guest_rating / guest_review_count
    else 
      average_rating = 0
    end
    return average_rating
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    # @profile = Profile.find(params[:id])
    @guest_reviews = []
    if @profile.user.stays.length > 0
      @profile.user.stays.each do |stay|
        if stay.guestreview
          @guest_reviews << stay.guestreview
        end
      end
    end

  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: "Profile was successfully created." }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: "Profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_profile
    @profile = Profile.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :created_at, :bio, :karma_coins, :host_rating, :guest_rating, :user_id, :uploaded_image)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
    def increase_karma(coins)
        update_attributes(:karma_coins => karma_coins += coins)
    end
  
    def decrease_karma(coins)
        update_attributes(:karma_coins => karma_coins -= coins)
    end
end

app/views/profiles/_current_user_profile.html.erb
<p id="notice"><%= notice %></p>
<div class="profile-wrapper">
  <div class="profile-left">
    <% if @profile.first_name && @profile.last_name %>
      <h1 class="center-text">
        <strong> <%= @profile.first_name %> <%= @profile.last_name%>'s Profile</strong>
      </h1>
      <p>
      <strong>member since: <%= @profile.created_at.day %> <%= I18n.l(@profile.created_at, format: "%B") %> <%= @profile.created_at.year %></strong>
      </p>
    <% else %>
      <p class="center-text"> <strong>Welcome to your profile page! Feel free to browse through accommodation but in order to apply to stay at a location we'll need you to <%= link_to 'Finish editing your profile', edit_profile_path(@profile) %></strong></p>
    <% end %>
    
    <% if @profile.uploaded_image.attached? %>
      <%= image_tag @profile.uploaded_image.service_url, class: 'image-size' %>
    <% else %>
      <p>No image for this profile  <%= link_to 'Finish editing your profile', edit_profile_path(@profile) %></p></p>
    <% end %>

      <p>
      <strong>Name:</strong>
      <% if @profile.first_name && @profile.last_name %>
        <%= @profile.first_name %> <%= @profile.last_name %></p>
      <% else %>
        <%= link_to 'Finish editing your profile', edit_profile_path(@profile) %></p>
      <% end %>
      <p>
        <strong>Email:</strong> <%= @profile.user.email %>
      </p>

      <p>
      <strong>Karma balance:</strong>
      <% if @profile.karma_coins %>
        <%= image_tag '/img/kksym.png', class: 'kksym' %> <%= @profile.karma_coins %>
      <% else %>
        <strong>zero</strong> Host your first guest to earn some <%= image_tag '/img/kksym.png', class: 'kksym' %>arma Coins!</p>
      <% end %>
    <p>
      <strong>Bio:</strong>
      <% if @profile.bio %>
        <%= @profile.bio %></p>
      <% else %>
        <%= link_to 'Finish editing your profile', edit_profile_path(@profile) %></p>
      <% end %>

    <p>
      <strong>Host rating:</strong>
      <% if @profile.host_rating > 0 %>
        <%= convert_float_to_1sf(@profile.get_host_rating) %> / 5</p>
      <% else %>
        No rating recieved yet</p>
      <% end %>

    <p>
      <strong>Guest rating:</strong>
      <% if @profile.guest_rating > 0 %>
        <%= convert_float_to_1sf(@profile.get_guest_rating) %> / 5
      <% else %>
        No rating recieved yet</p>
      <% end %>

    <p>
    <% if @profile.user.role_id == 2 %>
      <%= @profile.user.role.privilege %>. <%= link_to("Upgrade to premium today!", upgrade_path) %> 
    <% elsif @profile.user.role_id == 3 %>
      <%= @profile.user.role.privilege %> 
    <% end %>
    
    <% if @profile.user.role_id == 3 %>
      <%= image_tag '/img/premium_badge.png', class: 'premium' %>
    <% end %>

    </p>

    <p><%= link_to 'Edit Profile', edit_profile_path(@profile) %> | <%= link_to 'Edit Email & Password', edit_user_registration_path(current_user) %></p>
  </div>
  <div class="profile-right">
    <div class="accommodation-section">
    <% if @profile.user.accommodation %>
    <div class="accom-title">
      <p><strong>Your Listed Accommodation</strong></p>
      <p id="accom-name"><strong><%= @profile.user.accommodation.name %></strong></p>
    </div>
    <% if @profile.user.accommodation.hero_image.attached? %>
      <%= image_tag @profile.user.accommodation.hero_image.service_url, class: 'accom-img-size' %>
    <% else %>
      <p>No Image has been provided for this Accommodation</p>
    <% end %>
    <div class="prof-button-flex">
      <%= button_to "View stays hosted at property", accommodation_stays_path(accommodation_id: @profile.user.accommodation.id), method: :get, class: "accom-stay-button" %><%= button_to "View property listing", accommodation_path(@profile.user.accommodation.id), method: :get, class: "stay-accom-button" %>
    </div>
    <% else %>
      <p> 
        <strong>
          You need to add a property so that you can host guests.
        </strong>
      </p>
      <%= button_to "Add Property", new_accommodation_path, params: {:profile_id => @profile.user.id}, method: :get, class: "add-accom-button" %>
    <% end %>
     
    </div>
    <div class="guest-section">
      <% if @profile.first_name && @profile.last_name %>
        <p> <strong><%= @profile.first_name %> <%= @profile.last_name  %>'s Guest Profile</strong> </p>
      <% else %>
        <p><strong>Guest Profile</strong></p>
      <% end %>

      <% if @profile.user.stays.length > 0 %>
        <div class="profile-stay-section">
        <p class="stay-header"><strong>Your Most Recent Stay Activity</strong></p>
        <p>
        <strong>Accommodation Name: </strong><%= @profile.user.stays.last.accommodation.name %>
        </p>
        <p>
        <strong>Start date: </strong><%= @profile.user.stays.last.start_date.day %> <%= I18n.l(@profile.user.stays.last.start_date, format: "%B") %> <%= @profile.user.stays.last.start_date.year %> | 
        <strong>End date: </strong><%= @profile.user.stays.last.end_date.day %> <%= I18n.l(@profile.user.stays.last.end_date, format: "%B") %> <%= @profile.user.stays.last.end_date.year %>
        </p>
        <p>
          <strong>Request Status:
              <% if @profile.user.stays.last.state_pending? and @profile.user.stays.last.end_date < Time.now %>
                <span class="pending">Stay request is expired </span>
              <% elsif @profile.user.stays.last.state_pending? %>
                <span class="pending">Stay request is pending</span>
              <% elsif @profile.user.stays.last.rejected? %>
                <span class="rejected">Stay Declined</span>
              <% elsif @profile.user.stays.last.confirmed? %>
                <span class="confirmed">Stay Accepted</span>
              <% elsif @profile.user.stays.last.cancelled? %>
              <span class="rejected">Stay Cancelled</span></p>
              <% end %>
              </strong>
        </p>
        </div>
      <% end %>
      
      <%= button_to "View your stays as a guest", guest_stays_path(guest_id: @profile.user.id ), method: :get, class: "stay-profile-button" %>

    </div>
  </div>
</div>

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: 'devise-field' %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: 'devise-field' %>
  </div>

  <div class="valign">
    <%= form.label :bio, 'About Me', class: 'text-field-label' %>
    <%= form.text_area :bio, class: 'devise-field' %>
  </div>

  <div class="field">
  <%= form.label :uploaded_image, 'Profile Image' %>
  <%= form.file_field :uploaded_image %>
  <p id="best-results">(For best results image should be larger than 400 x 400 pixels) </p>
  </div>

  <div class="actions">
    <%= form.submit class: 'devise-button-update' %>
  </div>
<% end %>

app/views/profiles/_other_user_profile.html.erb
<p id="notice"><%= notice %></p>
<div class="profile-wrapper">
  <div class="profile-left">
    <% if @profile.first_name && @profile.last_name %>
      <h1 class="center-text">
        <strong> <%= @profile.first_name %> <%= @profile.last_name%>'s Profile</strong>
      </h1>
      <p>
      <strong>member since: <%= @profile.created_at.day %> <%= I18n.l(@profile.created_at, format: "%B") %> <%= @profile.created_at.year %></strong>
      </p>
    <% else %>
      <p class="center-text"> <strong>This User is yet to complete their profile, check back later for more information.</strong></p>
    <% end %>
    
    <% if @profile.uploaded_image.attached? %>
      <%= image_tag @profile.uploaded_image.service_url, class: 'image-size' %>
    <% else %>
      <p>No image has been added to this profile</p>
    <% end %>

      <p>
      <strong>Name:</strong>
      <% if @profile.first_name && @profile.last_name %>
        <%= @profile.first_name %> <%= @profile.last_name %></p>
      <% else %>
       <p>User is yet to add a name to their profile</p>
      <% end %>
    <p>
      <strong>Bio:</strong>
      <% if @profile.bio %>
        <%= @profile.bio %></p>
      <% else %>
       User is yet to add a bio to their profile</p>
      <% end %>

    <p>
      <strong>Host rating:</strong>
      <% if @profile.host_rating > 0%>
        <%= convert_float_to_1sf(@profile.get_host_rating) %> / 5</p>
      <% else %>
        No rating recieved yet</p>
      <% end %>

    <p>
      <strong>Guest rating:</strong>
      <% if @profile.guest_rating > 0 %>
        <%= convert_float_to_1sf(@profile.get_guest_rating) %> / 5
      <% else %>
        No rating recieved yet</p>
      <% end %>

  </div>
  <div class="profile-right">
    <div class="accommodation-section">
    <% if @profile.user.accommodation %>
      <% if @profile.first_name && @profile.last_name %>
        <p><strong><%= @profile.first_name %>'s Accommodation: <%= @profile.user.accommodation.name %></strong></p>
      <% else %>
        <p><strong>Accommodation: <%= @profile.user.accommodation.name %></strong></p>
      <% end %>
      <% if @profile.user.accommodation.hero_image.attached? %>
        <%= image_tag @profile.user.accommodation.hero_image.service_url, class: 'accom-img-size' %>
      <% else %>
      <p>No Image has been provided for this Accommodation</p>
      <% end %>
      <div class="prof-button-flex">
        <%= button_to "View Property Listing", accommodation_path(@profile.user.accommodation.id), method: :get, class: "stay-accom-button" %>
        <%= button_to "View Reviews", accommodationreviews_path, method: :get, params: {accommodation_id: @profile.user.accommodation.id}, class: "accom-stay-button" %>
      </div>
    <% else %>
       <div class="prof-button-flex">
        <p>User does not have accommodation added yet</p>
      </div>
    <% end %>
     
    </div>
    <div class="guest-section">
      <% if @profile.first_name && @profile.last_name %>
        <p> <strong><%= @profile.first_name %> <%= @profile.last_name  %>'s Guest Profile</strong> </p>
      <% else %>
        <p><strong>Guest Profile</strong></p>
      <% end %>
      <% if @guest_reviews.length > 0 %>
      <div class="profile-stay-section">
          <p class="stay-header"><strong><%= @profile.first_name %>'s latest review as a guest</strong></p>
          <p>
            <strong>Reviewed by: <%= link_to "#{@guest_reviews.last.stay.accommodation.host.profile.first_name} #{@guest_reviews.last.stay.accommodation.host.profile.last_name}", profile_path(@guest_reviews.last.stay.accommodation.host.id) %></strong>
          </p>
          <p>
          <strong>Review Date: </strong><%= @guest_reviews.last.created_at.day %> <%= I18n.l(@guest_reviews.last.created_at, format: "%B") %> <%= @guest_reviews.last.created_at.year %>
          <p>
          <strong>Cleanliness: </strong><%= @guest_reviews.last.cleanliness_rating %>
          <strong>Communication: </strong><%= @guest_reviews.last.communication_rating %>
          <strong>Easy to host: </strong><%= @guest_reviews.last.ease_of_hosting_rating %>
          </p>
          <p>
            <strong>Comments: </strong><%= @guest_reviews.last.comments %>
          </p>
        </div> 
        <%= button_to "View Guest Reviews", guestreviews_path, method: :get, params: {guest_id: @profile.user.id}, class: "stay-profile-button" %>
      <% else %>
        <p>
          User does not have any reviews as a guest yet.
        </p>
      <% end %>
      
        
    </div>
  </div>
</div>

app/views/profiles/edit.html.erb
<div class="hero-container-edit-page">'
  <%= image_tag("/img/editprofile.jpg",  alt: "beers on the couch", class: "hero-image") %>
  <div class="devise">
    <h1>Edit Your Profile</h1>

    <%= render 'form', profile: @profile %>

    <%= link_to 'Back', @profile %>
     
  </div>
  </div>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Created at</th>
      <th>Bio</th>
      <th>Karma coins</th>
      <th>Host rating</th>
      <th>Guest rating</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.first_name %></td>
        <td><%= profile.last_name %></td>
        <td><%= profile.created_at %></td>
        <td><%= profile.bio %></td>
        <td><%= profile.karma_coins %></td>
        <td><%= profile.host_rating %></td>
        <td><%= profile.guest_rating %></td>
        <td><%= profile.user %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
  
<% if current_user == @profile.user %>
  <%= render 'current_user_profile' %>
<% else %>
  <%= render 'other_user_profile' %>
<% end %>