config/routes.rb
Rails.application.routes.draw do
  resources :guestreviews
  resources :accommodationreviews
  resources :stays 
  resources :messages, only: [:create, :destroy]
  resources :accommodations
  resources :profiles
  devise_for :users
  resources :charges
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "pages#index"

  get "guest/:guest_id/stays" => "stays#index", as: "guest_stays"
  get "accommodation/:accommodation_id/stays" => "stays#index", as: "accommodation_stays"
  get "pages/about" => "pages#about", as: "about_page"
  get "pages/upgrade" => "pages#upgrade", as: "upgrade"
  get "stay/update-status" => "stays#update_status", as: "update_status"
end

app/models/stay.rb
class Stay < ApplicationRecord
  belongs_to :accommodation
  belongs_to :guest, :class_name => 'User'
  has_many :messages
  has_one :accommodationreview
  has_one :guestreview

  def clear_state
    self.confirmed = false
    self.rejected = false
    self.cancelled = false
  end

  def set_state_pending
    self.clear_state
  end

  def set_state_confirmed
    self.clear_state
    self.confirmed = true
  end

  def set_state_rejected
    self.clear_state
    self.rejected = true
  end

  def set_state_cancelled
    self.clear_state
    self.cancelled = true
  end

  def state_pending?
    (!self.confirmed and !self.rejected and !self.cancelled)
  end

  def state_confirmed?
    self.confirmed
  end

  def state_rejected?
    self.rejected
  end

  def state_cancelled?
    self.cancelled
  end
end

app/controllers/stays_controller.rb
class StaysController < ApplicationController
  before_action :set_stay, only: [:show, :edit, :update, :destroy]
  # GET /stays
  # GET /stays.json
  def index

    if params[:accommodation_id]
      @accommodation = Accommodation.find(params[:accommodation_id])
      @stays = @accommodation.stays
      @title = @accommodation.name
    elsif params[:guest_id]
      @guest = User.find(params[:guest_id]).profile
      @stays = User.find(params[:guest_id]).stays
      @title = "#{@guest.first_name} #{@guest.last_name}"
    end
    if @stays.first
      authorize(@stays.first)
    end
  end

  def guest
  end

  def accom
  end

  # GET /stays/1
  # GET /stays/1.json
  def show
    authorize(@stay)
    if params[:accommodation_id]
      @accommodation = Accommodation.find(params[:accommodation_id])
      @title = @accommodation.name
    elsif params[:guest_id]
      @guest = User.find(params[:guest_id]).profile
      @title = "#{@guest.first_name} #{@guest.last_name}"
    end

    @stay_length = (@stay.end_date - @stay.start_date) / 1.day.round
    @stay_cost = @stay_length * @stay.accommodation.accomtype.cost

  end

  # GET /stays/new
  def new
    @stay = Stay.new
  end

  # GET /stays/1/edit
  def edit
    @stay = Stay.find(params[:id])
    authorize(@stay)
  end

  # POST /stays
  # POST /stays.json
  def create
    @stay = Stay.new(stay_params)
    @stay_length = (@stay.end_date - @stay.start_date) / 1.day.round
    @stay_cost = @stay_length * @stay.accommodation.accomtype.cost
    
    if current_user.profile.karma_coins < @stay_cost
      respond_to do |format|
        format.html { redirect_to accommodation_path(@stay.accommodation, guest_id: current_user.id), notice: "You do not have enough Karma Coins to request this stay." }
      end
    else
      @stay.guest = User.find(current_user.id)
      @stay.created_at = Time.now
      @stay.confirmed = false
      @stay.rejected = false

      respond_to do |format|
        if @stay.save
          format.html { redirect_to stay_path(@stay, guest_id: @stay.guest.id), notice: "Stay was successfully created." }
          format.json { render :show, status: :created, location: @stay }
        else
          format.html { render :new }
          format.json { render json: @stay.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /stays/1
  # PATCH/PUT /stays/1.json
  def update
    respond_to do |format|
      if @stay.update(stay_params)
        format.html { redirect_to stay_path(@stay, guest_id: @stay.guest.id), notice: "Stay was successfully updated." }
        format.json { render :show, status: :ok, location: @stay }
      else
        format.html { render :edit }
        format.json { render json: @stay.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_status
    @stay = Stay.find(params[:stay])
    authorize(@stay)
    @stay_length = (@stay.end_date - @stay.start_date) / 1.day.round
    @stay_cost = @stay_length * @stay.accommodation.accomtype.cost
    if params[:confirmed]
      @stay.set_state_confirmed
      @stay.accommodation.host.profile.increment!(:karma_coins, @stay_cost) 
      @stay.accommodation.host.save! 
      @stay.guest.profile.decrement!(:karma_coins, @stay_cost) 
      @stay.guest.profile.save!
      @stay.save!
      redirect_to stay_path(@stay, accommodation_id: params[:accommodation_id])
    elsif params[:rejected]
      @stay.set_state_rejected
      @stay.save!
      redirect_to stay_path(@stay, accommodation_id: params[:accommodation_id])
    elsif params[:cancelled]
      @stay.set_state_cancelled
      @stay.accommodation.host.profile.decrement!(:karma_coins, @stay_cost) 
      @stay.accommodation.host.save! 
      @stay.guest.profile.increment!(:karma_coins, @stay_cost) 
      @stay.guest.profile.save!  
      @stay.save!
      if params[:accommodation_id]
        redirect_to stay_path(@stay, accommodation_id: params[:accommodation_id])
      elsif params[:guest_id]
        redirect_to stay_path(@stay, accommodation_id: params[:guest_id])
      end    
    end
  end 


  private

  # Use callbacks to share common setup or constraints between actions.
  def set_stay
    print params
    @stay = Stay.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def stay_params
    params.require(:stay).permit(:accommodation_id, :start_date, :end_date, :created_at)
  end
end

app/helpers/stays_helper.rb
module StaysHelper
end

app/views/stays/_form.html.erb
<div class ="form-inline">
  <%= form_with(model: stay, local: true) do |form| %>
    <% if stay.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(stay.errors.count, "error") %> prohibited this stay from being saved:</h2>

        <ul>
        <% stay.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="field">
      <%= form.label :start_date %>
      <%= form.date_select :start_date, {order: [:day, :month, :year] }, class: 'devise-field' %>
    </div>

    <div class="field">
      <%= form.label :end_date %>
      <%= form.date_select :end_date, {order: [:day, :month, :year] }, class: 'devise-field' %>
    </div>
    <%= form.hidden_field :accommodation_id, value: accommodation_id %>
    <%= form.submit "Request Stay!", class: 'stay-button' %>
  <% end %>
</div>

app/views/stays/edit.html.erb
<div class="stay-flex">
    <h1>Editing Stay at <%= @stay.accommodation.name %></h1>
    <%= render partial: 'form', locals: { stay: @stay, accommodation_id: params[:accommodation_id] }%>
    <%= link_to 'Back', @stay%>
</div>

app/views/stays/index.html.erb
<p id="notice"><%= notice %></p>
<% if params[:accommodation_id] %>
  <h1 class="center-text">All Stays Hosted by <%= @accommodation.host.profile.first_name %> <%= @accommodation.host.profile.last_name %> at <%= @title %></h1>
<% else %>
  <h1><h1 class="center-text">All Stays for <%= @title %></h1>
<% end %>

<div class="results-wrapper">
  <% @stays.reverse.each do |stay| %>
    <div class="stay-wrapper">
      <div class="accom-img-container">
        <% if params[:guest_id] %>
          <% if stay.accommodation.hero_image.attached? %>
              <%= image_tag stay.accommodation.hero_image.service_url, class: 'accom-img-thumb' %>
          <% else %>
              <p>No Image has been provided for this Accommodation</p>
          <% end %>
        <% elsif params[:accommodation_id] %>
           <% if stay.guest.profile.uploaded_image.attached? %>
              <%= image_tag stay.guest.profile.uploaded_image.service_url, class: 'accom-img-thumb' %>
          <% else %>
              <p>No Image has been provided for this Guest</p>
          <% end %>
        <% end %>
      </div>
      <div class="stay-para-flex">
        <% if params[:accommodation_id] %>
          <p><strong>Guest:</strong> <%= stay.guest.profile.first_name %> <%= stay.guest.profile.last_name %></p>
        <% else %>
          <p><strong>
            <%= link_to("#{stay.accommodation.name}", accommodation_path(stay.accommodation.id), class: 'accom-link') %>
          </strong></p>
        <% end %>  

        <p>
        <strong>Start Date: </strong><%= stay.start_date.day %> <%= I18n.l(stay.start_date, format: "%B") %> <%= stay.start_date.year %>
        <strong>End Date: </strong><%= stay.end_date.day %> <%= I18n.l(stay.end_date, format: "%B") %> <%= stay.end_date.year %>
        </p>
        
           <p>
            <strong>Request Status:
            <% if stay.state_pending? and stay.end_date < Time.now %>
              <span class="pending">Stay request is expired </span>
            <% elsif stay.state_pending? %>
              <span class="pending">Stay request is pending</span>
            <% elsif stay.rejected? %>
              <span class="rejected">Stay Declined</span>
            <% elsif stay.confirmed? %>
              <span class="confirmed">Stay Accepted</span>
            <% elsif stay.cancelled? %>
            <span class="rejected">Stay Cancelled</span></p>
            <% end %>
            </strong>
          </p>

        <div class="prof-button-flex">
          <% if stay.confirmed == false && stay.rejected == false %>  
            <% if params[:guest_id] %>
              <%= button_to 'Edit Stay', edit_stay_path(stay), params: {:accommodation_id => stay.accommodation.id}, method: :get, class: 'view-stay-button' %>
            <% end %>
          <% end %>
          <% if params[:accommodation_id] %>
            <%= button_to 'View Stay', stay, params: {:accommodation_id => @accommodation.id}, method: :get, class: 'view-stay-button' %>
          <% elsif params[:guest_id] %>
            <%= button_to 'View Stay', stay, params: {:guest_id => @guest.id}, method: :get, class: 'view-stay-button' %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/stays/new.html.erb
<h1> Request a stay at <%=Accommodation.find(params[:accommodation_id]).name%> <h1>    

<%= render partial: 'form', locals: { stay: @stay, accommodation_id: params[:accommodation_id] }%>
</div>
<%= link_to 'Back', stays_path %>

app/views/stays/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="center-text">
  Stay for <%= @stay.guest.profile.first_name %> <%= @stay.guest.profile.last_name %> at <%= @stay.accommodation.name %>
</h1>
<div class ="top-container">
  <div class="left-container">

    <p>
      <strong>Guest:</strong>
      <%= link_to "#{@stay.guest.profile.first_name} #{@stay.guest.profile.last_name}", profile_path(@stay.guest.id) %>
    </p>

    <p>
      <strong>Host:</strong>
      <%= link_to "#{@stay.accommodation.host.profile.first_name} #{@stay.accommodation.host.profile.last_name}", profile_path(@stay.accommodation.host.id) %>
    </p>

    <p>
      <strong>Accommodation:</strong>
      <%= link_to "#{@stay.accommodation.name}", accommodation_path(@stay.accommodation.id) %>
    </p>

    <p>
      <strong>Stay Requested On:</strong>
      <%= @stay.created_at.day %> <%= I18n.l(@stay.created_at, format: "%B") %> <%= @stay.created_at.year %>
    </p>

    <p>
      <strong>Start date:</strong>
      <%= @stay.start_date.day %> <%= I18n.l(@stay.start_date, format: "%B") %> <%= @stay.start_date.year %>
    </p>

    <p>
      <strong>End date:</strong>
      <%= @stay.end_date.day %> <%= I18n.l(@stay.end_date, format: "%B") %> <%= @stay.end_date.year %>
    </p>

    <p>
      <strong>Length:</strong>
        <% if @stay_length == 1 %>
          <%= @stay_length %> Night
        <% else %>
          <%= @stay_length %> Nights
        <% end %>
    </p>

    <p>
      <strong>Cost:</strong>
      <%= image_tag '/img/kksym.png', class: 'kksym' %><%= @stay_cost %>
    </p>

    <div class="host-container">
      <% if params[:accommodation_id] %>
        <% if @stay.guest.profile.uploaded_image.attached? %>
          <%= image_tag @stay.guest.profile.uploaded_image.service_url, class: 'accom-prof-img-size' %>
        <% end %>
        <div class = "host-container-text">
          <p> Your Guest is <%= link_to("#{@stay.guest.profile.first_name} #{@stay.guest.profile.last_name}", profile_path(@stay.guest)) %></p>
          <%= button_to "View Profile", profile_path(@stay.guest), method: :get, class: 'host-button'   %>
        </div>
      <% elsif params[:guest_id] %>
        <% if @stay.accommodation.host.profile.uploaded_image.attached? %>
          <%= image_tag @stay.accommodation.host.profile.uploaded_image.service_url, class: 'accom-prof-img-size' %>
        <% end %>
        <div class = "host-container-text">
          <p> Your Host is <%= link_to("#{@stay.accommodation.host.profile.first_name} #{@stay.accommodation.host.profile.last_name}", profile_path(@stay.accommodation.host)) %></p>
          <%= button_to "View Profile", profile_path(@stay.accommodation.host), method: :get, class: 'host-button'   %>
        </div>
      <% end %>
    </div>
    <p>

  <p>
    <strong>Request Status:</strong>
    <% if @stay.state_pending? and @stay.end_date < Time.now %>
      <%# if state is expired, print expired %>
      <span class="rejected">Stay Request Expired</span></p>
    <% elsif @stay.state_pending? %>
      <%# if state is pending, print pending and make approve and reject buttons available %>
      <span class="pending">Stay request is pending</span>
      <% if current_user == @stay.accommodation.host %>
        <div class="prof-button-flex">
          <%= button_to "Approve Stay", update_status_path, method: :get, params: {stay: @stay, accommodation_id: @stay.accommodation.id, confirmed: true}, class: 'approve-button' %>
          <%= button_to "Decline Stay", update_status_path, method: :get, data: { confirm: "Are you sure? This cannot be undone." }, params: {stay: @stay, accommodation_id: @stay.accommodation.id, rejected: true}, class: 'reject-button' %>
        </div>
      <% end %>
    <% elsif @stay.state_confirmed?  %>
      <%# if state is approved, print approved and 
      < if time passed make add review available >
      <%# else make cancel available %>
      <span class="confirmed">Stay Accepted</span></p>
      <% if current_user == @stay.guest %>
          <% if @stay.end_date < Time.now %>
            <% if !@stay.accommodationreview %>
              <%= button_to 'Leave a review for this stay', new_accommodationreview_path, method: :get, params: {stay_id: @stay.id, guest_id: @guest.id}, class: 'review-button' %>
            <% end %>
        <% else %>
            <% if params[:accommodation_id] %>
              <p>Unable to Host this stay anymore? </p><%= button_to "Cancel Stay", update_status_path, method: :get, data: { confirm: "Are you sure? This cannot be undone." }, params: {stay: @stay, accommodation_id: @stay.accommodation.id, cancelled: true}, class: 'reject-button' %>
            <% elsif params[:guest_id] %>
              <p>Unable to attend this stay anymore? </p><%= button_to "Cancel Stay", update_status_path, method: :get, data: { confirm: "Are you sure? This cannot be undone." }, params: {stay: @stay, guest_id: @stay.guest.id, cancelled: true}, class: 'reject-button' %>
            <% end %>
        <% end %>
      <% elsif current_user == @stay.accommodation.host %>
            <% if @stay.end_date < Time.now %>
              <% if !@stay.guestreview %>
                <%= button_to 'Leave a review for this Guest', new_guestreview_path, method: :get, params: {stay_id: @stay.id, accommodation_id: @accommodation.id}, class: 'review-button' %>
              <% end %>
            <% else %>
              <p>Unable to host this stay anymore?</p><%= button_to "Cancel Stay", update_status_path, method: :get, data: {confirm: "Are you sure? This cannot be undone." }, params: {accommodation_id: @stay.accommodation.id, stay: @stay, cancelled: true}, class: 'reject-button' %>
            <% end %>
        <% end %>
    <% elsif @stay.state_rejected? %>
      <%# if state is rejected, print rejected %>
      <span class="rejected">Stay Declined</span></p>
    <% elsif @stay.state_cancelled? %>
      <%# if state is cancelled, print cancelled %>
      <span class="rejected">Stay Cancelled</span></p>
    <% end %>
  </p>

      <p>
        <% if current_user == @stay.guest %>
          <% if !@stay.confirmed && !@stay.rejected %> 
            <%= link_to 'Edit Stay', edit_stay_path(@stay, {:accommodation_id => @stay.accommodation.id}) %> |
          <% end %>
        <% end %>

        <% if params[:accommodation_id] %>
          <%= link_to 'Back', stays_path({accommodation_id: @accommodation.id}) %>    
        <% elsif params[:guest_id] %>
          <%= link_to 'Back', stays_path({guest_id: @guest.id}) %>
        <% end %>
      </p>
  </div>  
  <div class="right-container">
    <% if @stay.accommodation.hero_image.attached? %>
        <%= image_tag @stay.accommodation.hero_image.service_url, class: 'accom-image-size' %>
    <% else %>
      <p>No Hero image for this accommodation has been added</p>
    <% end %>
    <%= link_to(@stay.accommodation.name, accommodation_path(@stay.accommodation)) %> 
  </div>
</div>
<div id="review-section">
  
    <% if @stay.accommodationreview %>
      <div class="accom-review">
      <div class="review-title">
        <% if @stay.guest.profile.uploaded_image.attached? %>
          <%= image_tag @stay.guest.profile.uploaded_image.service_url, class: 'review-image-thumb' %>
        <% end %>
        <p> <strong><%= @stay.guest.profile.first_name %>'s Review of <%= @stay.accommodation.name %></strong></p>
      </div>
        <p>
          Communication: <%= @stay.accommodationreview.communication_rating %> | 
          Location: <%= @stay.accommodationreview.location_rating %> | 
          Cleanliness: <%= @stay.accommodationreview.cleanliness_rating %> |
          Ammenities: <%= @stay.accommodationreview.ammenities_rating %> | 
          Host: <%= @stay.accommodationreview.host_rating %> 
        </p>

        <div class="comments">
          <p><strong>Comments</strong></p>
          <p>  
            <%= @stay.accommodationreview.comments %>
          </p>
        </div>  

      </div>
    <% end %>

    <% if @stay.guestreview %>
      <div class="guest-review">
        <div class="review-title">
          <% if @stay.accommodation.host.profile.uploaded_image.attached? %>
            <%= image_tag @stay.accommodation.host.profile.uploaded_image.service_url, class: 'review-image-thumb' %>
          <% end %>
          <p> <strong><%= @stay.accommodation.host.profile.first_name %>'s Review of <%= @stay.guest.profile.first_name %> as a Guest</strong></p>
        </div>
        <p>
          Communication: <%= @stay.guestreview.communication_rating %> | 
          Cleanliness: <%= @stay.guestreview.cleanliness_rating %> |
          Easy to host: <%= @stay.guestreview.ease_of_hosting_rating %> 
        </p>

        <div class="comments">
          <p><strong>Comments</strong></p> 
          <p>  
           <%= @stay.guestreview.comments %>
          </p>
        </div> 
        
      </div>
    <% end %>

</div>
<div class="message-section">
  <p>
  <strong>Create a New Message</strong>
  <% if params[:accommodation_id] %>
    <%= render partial: '/messages/form', locals: {message: Message.new, user_id: @accommodation.host.id, accommodation_id: @accommodation.id, stay_id: @stay.id} %>
  <% elsif params[:guest_id] %>
    <%= render partial: '/messages/guest_form', locals: {message: Message.new, user_id: @guest.id, guest_id: @guest.id, stay_id: @stay.id} %>
  <% end %>
  
  </p>
  <p>
    <strong>Messages</strong>
  </p>
  <p>
    (recent messages displayed at top)
  </p>
  <div id="messages-container">
    <% @stay.messages.reverse.each do |message| %>
      <p>
        <% if User.find(message.user_id).profile.uploaded_image.attached? %>
          <%= image_tag User.find(message.user_id).profile.uploaded_image.service_url, class: 'image-thumb' %>
        <% end %>
        <%= User.find(message.user_id).profile.first_name %> :
        <%= message.content %>
        <% if current_user == @stay.accommodation.host && current_user == User.find(message.user_id) %>
          <%= link_to 'Delete', message_path(message, accommodation_id: @stay.accommodation.id, stay_id: @stay.id), method: :delete, data: { confirm: 'Are you sure? This cannot be undone' }, params: {accommodation_id: @stay.accommodation.id, stay_id: @stay.id} %>
        <% elsif current_user == @stay.guest && current_user == User.find(message.user_id) %>
          <%= link_to 'Delete', message_path(message, guest_id: @stay.guest.id, stay_id: @stay.id), method: :delete, data: { confirm: 'Are you sure? This cannot be undone' } %>
        <% end %>
      </p>
    <% end %>
  </div>
</div>