config/routes.rb
Rails.application.routes.draw do
  resources :guestreviews
  resources :accommodationreviews
  resources :stays 
  resources :messages, only: [:create, :destroy]
  resources :accommodations
  resources :profiles
  devise_for :users
  resources :charges
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "pages#index"

  get "guest/:guest_id/stays" => "stays#index", as: "guest_stays"
  get "accommodation/:accommodation_id/stays" => "stays#index", as: "accommodation_stays"
  get "pages/about" => "pages#about", as: "about_page"
  get "pages/upgrade" => "pages#upgrade", as: "upgrade"
  get "stay/update-status" => "stays#update_status", as: "update_status"
end

app/models/accommodation.rb
class Accommodation < ApplicationRecord
  belongs_to :host, :class_name => 'User'
  belongs_to :accomtype
  has_many :stays
  has_one_attached :hero_image
  has_one_attached :interior_image
  geocoded_by :city
  validates :description, length: { maximum: 200 }
  after_validation :geocode, :if => :city_changed?

  def update_accommodation_rating(communication_rating, ammenities_rating, location_rating, cleanliness_rating)

    # calculate total reviews by counting stay reviews
    accom_review_count = 0
    self.stays.each do |stay|
      if stay.accommodationreview
        accom_review_count =  accom_review_count + 1
      end
    end

    # Get average of this user's ratings
    users_average_rating = calculate_average([communication_rating.to_i, ammenities_rating.to_i, location_rating.to_i, cleanliness_rating.to_i])
    # users_average_rating = (communication_rating.to_i + ammenities_rating.to_i + location_rating.to_i + cleanliness_rating.to_i) / 5.0

    # add new rating to current accommodation rating
    self.accommodation_rating = self.accommodation_rating + users_average_rating
    # divide rating by total stays
    average_rating = self.accommodation_rating / accom_review_count
    self.save!
  end

  def get_accommodation_rating()
    # calculate total reviews by counting stay reviews
    # calculate total reviews by counting stay reviews
    accom_review_count = 0

    self.stays.each do |stay|
      if stay.accommodationreview
        accom_review_count =  accom_review_count + 1
      end
    end

    # divide rating by total stays
    if accom_review_count != 0
      average_rating = self.accommodation_rating / accom_review_count
    else
      average_rating = 0
    end
    return average_rating
  end
end

app/controllers/accommodations_controller.rb
class AccommodationsController < ApplicationController
  before_action :set_accommodation, only: [:show, :edit, :update, :destroy]

  # GET /accommodations
  # GET /accommodations.json
  def index
    if params[:search].present?
      @accommodations = Accommodation.near(params[:search], 50, :order => :distance)
    else
      @accommodations = Accommodation.all
    end
  end

  # GET /accommodations/1
  # GET /accommodations/1.jso
  def show
    @stay = Stay.new
  end

  # GET /accommodations/new
  def new
    authorize(Accommodation)
    @accommodation = Accommodation.new
    @host = params[:profile_id]
  end

  # GET /accommodations/1/edits
  def edit
    @accommodation = Accommodation.find(params[:id])
  end

  # POST /accommodations
  # POST /accommodations.json
  def create
    @accommodation = Accommodation.new(accommodation_params)
    @accommodation.date_created = Time.now
    @accommodation.host = User.find(params[:profile_id])
    authorize(@accommodation)
    @accommodation.accommodation_rating = 0
    respond_to do |format|
      if @accommodation.save!
        format.html { redirect_to @accommodation, notice: "Accommodation was successfully created." }
        format.json { render :show, status: :created, location: @accommodation }
      else
        format.html { render :new }
        format.json { render json: @accommodation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accommodations/1
  # PATCH/PUT /accommodations/1.json
  def update
    authorize(@accommodation)
    respond_to do |format|
      if @accommodation.update(accommodation_params)
        format.html { redirect_to @accommodation, notice: "Accommodation was successfully updated." }
        format.json { render :show, status: :ok, location: @accommodation }
      else
        format.html { render :edit }
        format.json { render json: @accommodation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accommodations/1
  # DELETE /accommodations/1.json
  def destroy
    authorize(@accommodation)
    @accommodation.destroy
    respond_to do |format|
      format.html { redirect_to accommodations_url, notice: "Accommodation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_accommodation
    @accommodation = Accommodation.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def accommodation_params
    params.require(:accommodation).permit(:name, :description, :country, :city, :address, :host_id, :available_start_date, :available_end_date, :accomtype_id, :hero_image, :interior_image, :accommodation_rating)
  end
end

app/helpers/accommodations_helper.rb
module AccommodationsHelper
end

app/views/accommodations/_form.html.erb
<%= form_with(model: accommodation, local: true) do |form| %>
  <% if accommodation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(accommodation.errors.count, "error") %> prohibited this accommodation from being saved:</h2>

      <ul>
      <% accommodation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'devise-field' %>
  </div>

  <div class="valign">
    <%= form.label :description, class: 'text-field-label' %>
    <%= form.text_area :description, class: 'devise-field' %>
  </div>

   <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, class: 'devise-field' %>
  </div>

  <div class="field">
  <%= form.label :city %>
    <%= form.select :city, options_for_select(city_select()), {} , class: 'devise-field'%>
  </div>

  <div class="field">
  <%= form.label :country %>
    <%= form.select :country, options_for_select(country_select()), {} , class: 'devise-field'%>
  </div>

  <div class="field">
    <%= form.label :available_start_date %>
    <%= form.date_select :available_start_date, {order: [:day, :month, :year]}, class: 'devise-field' %>
  </div>

  <div class="field">
    <%= form.label :available_end_date %>
    <%= form.date_select :available_end_date, {order: [:day, :month, :year] }, class: 'devise-field'%>
  </div>

  <div class="field">
  <%= form.label :accomtype_id %>
  <%= form.select :accomtype_id, options_for_select(accomtype_select()), {} , class: 'devise-field'%>
  </div>

  <div class="field">
    <%= form.label :hero_image, 'Hero exterior Image' %>
    <%= form.file_field :hero_image %>
    <p id="best-results">(For best results image should be larger than 400 x 400 pixels) </p>
  </div>

  <div class="field">
    <%= form.label :interior_image, 'Interior Image' %>
    <%= form.file_field :interior_image %>
    <p id="best-results">(For best results image should be larger than 400 x 400 pixels) </p>
  </div>
  <input type="hidden" value="<%= @host %>" name="profile_id">
  <div class="actions">
    <%= form.submit class: 'devise-button-update-accom' %>
  </div>
<% end %>

app/views/accommodations/_no_results.html.erb
<h2 id="no-result">Whoops! We found no results for your search!</h2>

<h1>Where can I stay?</h1>

<p >Nah..Imastay is currently available in Major Cities in the following places:</p>
<p>
    <%= image_tag '/img/ukflag.svg', class: 'flag' %> The United Kingdom
    | <%= image_tag '/img/aus_flag.svg', class: 'flag' %> Australia
    | <%= image_tag '/img/nzflag.png', class: 'flag' %> New Zealand
</p>

app/views/accommodations/_no_search.html.erb
<h2>Use the search bar above to find a place to Stay!</h2>

<h1>Where can I stay?</h1>

<p>Nah..Imastay is currently available in Major Cities in the following places:</p>
<p>
    <%= image_tag '/img/ukflag.svg', class: 'flag' %> The United Kingdom
    | <%= image_tag '/img/aus_flag.svg', class: 'flag' %> Australia
    | <%= image_tag '/img/nzflag.png', class: 'flag' %> New Zealand
</p>

app/views/accommodations/edit.html.erb
<div class="hero-container-edit-page">'
  <%= image_tag("/img/editprofile.jpg",  alt: "beers on the couch", class: "hero-image") %>
  <div class="devise">
    <h1>Editing Accommodation</h1>

    <%= render 'form', accommodation: @accommodation %>
    <p>
    <%= link_to 'Back', @accommodation %>
    </p>
    
  </div>
</div>

app/views/accommodations/index.html.erb
<p id="notice"><%= notice %></p>
<div class="results-wrapper">
<p><%= render '/shared/searchform', class: 'searchform' %></p>

<% if params[:search].present? && @accommodations.length == 0 %>
    <%= render 'no_results'%>
<% end %>

<% if params[:search].present? %>
    <% @accommodations.each do |accommodation| %>
        <div class="accommodation-wrapper">
            <div class="accom-img-container">
                <% if accommodation.hero_image.attached? %>
                    <%= image_tag accommodation.hero_image.service_url, class: 'accom-img-thumb' %>
                <% else %>
                    <p>No Image has been provided for this Accommodation</p>
                <% end %>
            </div>
        <div class="accom-para-flex">
            <h3>
                <%= link_to accommodation.name, accommodation, class: 'accom-link' %>
            </h3>
            <p>
                <strong>Rating: </strong> <%= accommodation.get_accommodation_rating %>
            </p>
            <p>
                <strong>Bed type:</strong>  <%= accommodation.accomtype.name %>
                <strong>Cost:</strong> <%= image_tag '/img/kksym.png', class: 'kksym' %> <%= accommodation.accomtype.cost %>
            </p>
            
            <p>
                <%= accommodation.description %>
            </p>
            <p>
                <strong>Address:</strong> <%= accommodation.address %>
                <strong>City: </strong><%= accommodation.city %>
                <strong>Country:<%= accommodation.country %></strong> 
            </p>
            
            <p>
               <strong>Available from: </strong>  <%= accommodation.available_start_date.day %> <%= I18n.l(accommodation.available_start_date, format: "%B") %> <%= accommodation.available_start_date.year %>
               <strong>Available Until:</strong>  <%= accommodation.available_end_date.day %> <%= I18n.l(accommodation.available_start_date, format: "%B") %> <%= accommodation.available_end_date.year %>
            </p>
            <%= button_to "View Accommodation", accommodation, method: :get, class: "view-accom-button" %>
        </div>
     </div>
    <% end %>
<% else %>
    <%= render 'no_search' %>
<% end %>
</div>

app/views/accommodations/new.html.erb
<div class="hero-container-edit-page">'
  <%= image_tag("/img/editprofile.jpg",  alt: "beers on the couch", class: "hero-image") %>
  <div class="devise">

    <h1>New Accommodation</h1>

    <%= render 'form', accommodation: @accommodation %>

    <%= link_to 'Back', profile_path(current_user.profile) %>
  </div>
</div>

app/views/accommodations/show.html.erb
<p id="notice"><%= notice %></p>
<h1 class="center-text"><%= @accommodation.name %></h1>

<% if current_user %>
  <% if @accommodation != current_user.accommodation && profile_complete(current_user.profile) %>
    <p class="center-text">
      <%= link_to "Request to Stay at this Property", "/accommodations/#{@accommodation.id}/#request" %>
    </p>
  <% elsif @accommodation != current_user.accommodation %>
    <p class="center-text">
      <strong>
        <%= link_to 'To Request a Stay you must Finish editing your profile', edit_profile_path(current_user.profile) %></p>
      </strong>
    </p>
  <% end %>
<% end %>
  

<% if current_user && @accommodation.host.id == current_user.id %>
<p class="center-text">
<%= link_to 'Edit Your Property Listing', edit_accommodation_path(@accommodation) %>
</p>
<% end %>
<div class="top-container">
  <div class="left-container">
    <p>
      <strong>This Accommodation has been bookable since</strong>
      <%= @accommodation.date_created.day %> <%= I18n.l(@accommodation.date_created, format: "%B") %> <%= @accommodation.date_created.year %>
    </p>
      <p>
        <strong>Accomtype:</strong>
        <%= @accommodation.accomtype.name %>
      </p>

      <p>
        <strong>Cost Per Night:</strong>
        <%= image_tag '/img/kksym.png', class: 'kksym' %><%= @accommodation.accomtype.cost %>
      </p>

      <p>
        <strong>Address:</strong>
        <%= @accommodation.address %>
        <strong>City:</strong>
        <%= @accommodation.city %>
        <strong>Country:</strong>
        <%= @accommodation.country %>
      </p>

      <p>
        <strong>Accommodation rating:</strong>
        <%= convert_float_to_1sf(@accommodation.get_accommodation_rating) %> / 5
        <%= link_to "View Reviews", accommodationreviews_path(accommodation_id: @accommodation.id) %>
      </p>

      <p>
        <strong>Available start date:</strong>
        <%= @accommodation.available_start_date.day %> <%= I18n.l(@accommodation.available_start_date, format: "%B") %> <%= @accommodation.available_start_date.year %>
      </p>
      <p>
        <strong>Available end date:</strong>
        <%= @accommodation.available_end_date.day %> <%= I18n.l(@accommodation.available_start_date, format: "%B") %> <%= @accommodation.available_end_date.year %>
      </p>


      <div class="host-container">
        <% if @accommodation.host.profile.uploaded_image.attached? %>
          <%= image_tag @accommodation.host.profile.uploaded_image.service_url, class: 'accom-prof-img-size' %>
        <% end %>
        <% if current_user && @accommodation.host.id == current_user.id %>
          <div id="host-container-text">
              <p><strong><%= link_to "You", profile_path(current_user.id) %> are the host of this property</strong></p>
              <%= button_to "View Your Profile", profile_path(@accommodation.host.id), method: :get, class: "host-button" %>
          </div>
        <% else  %>
          <div id="host-container-text">
              <p><strong><%= link_to "#{@accommodation.host.profile.first_name} #{@accommodation.host.profile.last_name}", profile_path(@accommodation.host.id) %>  is the host of this property</strong></p>
              <%= button_to "View Host Profile", profile_path(@accommodation.host.id), method: :get, class: "host-button" %>
          </div>
        <% end %>
      </div>
  </div>
  <div class="right-container">
    <% if @accommodation.hero_image.attached? %>
        <%= image_tag @accommodation.hero_image.service_url, class: 'accom-image-size' %>
    <% else %>
      <p>No Hero image for this accommodation has been added</p>
    <% end %>

     <% if @accommodation.interior_image.attached? %>
      <%= image_tag @accommodation.interior_image.service_url, class: 'accom-image-size' %>
  <% else %>
    <p>No Interior image for this accommodation has been added</p>
  <% end %>
  </div>
</div>

<h1 class="center-text">Description</h1>
<p class="center-text"><%= @accommodation.description %></p>

<% if current_user %>
   <% if @accommodation.host.id != current_user.id && profile_complete(current_user.profile) %>
    <div class="stay-flex">
      <h1 id="request">Request to stay at this Property</h1>
      <p id="notice"><%= notice %></p>
      <p><strong>Your Karma Coin Balance:</strong> <%= image_tag '/img/kksym.png', class: 'kksym' %><%= current_user.profile.karma_coins %> </p>
      <p>
        <strong>Cost Per Night:</strong>
        <%= image_tag '/img/kksym.png', class: 'kksym' %><%= @accommodation.accomtype.cost %>
      </p>
      <%= render partial: '/stays/form', locals: {stay: @stay, accommodation_id: @accommodation.id}, class: 'form-inline' %>
    </div>
  <% elsif @accommodation != current_user.accommodation %>
    <p class="center-text">
      <strong>
        <%= link_to 'To Request a Stay you must Finish editing your profile', edit_profile_path(current_user.profile) %></p>
      </strong>
    </p>
  <% end %>
<% end %>
 



<% if current_user && @accommodation.host.id == current_user.id %>
<p class="center-text">
<%= link_to 'Edit Your Property Listing', edit_accommodation_path(@accommodation) %>
</p>
<% end %>